name: PexTabCompleter
version: ${project.version}
main: com.benzoft.pextabcompleter.PexTabCompleter
api-version: "1.13"
depend: [PermissionsEx]
authors: [Benz56]
description: Allows tab completion of PermissionsEx commands.
website: benzoft.com
permissions:
  pextabcompleter.use:
    description: Allows players to get tab suggestions for PEX commands.